apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmfile-demo-nginx
  labels:
    app.kubernetes.io/name: helmfile-demo-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: helmfile-demo-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helmfile-demo-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4-alpine
        ports:
        - containerPort: 80
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/templates/default.conf.template
          subPath: default.conf.template
          readOnly: true

      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: default.conf.template
              path: default.conf.template
